<!-- barcode -->
<h4>
	<p class="text-success">This is the barcode generated by the id of
		the book.</p>
</h4>
<img src="D:/barcode/<s:property value="id"/>.jpg">
<br>

<!-- the image of the booklocation -->
<h4>
	<p class="text-success">This is the image generated by the location
		of the book.</p>
</h4>

<img src="D:/booklocation/<s:property value="id"/>.png">
<br>

<p class="text-success"><s:property value="errorMessage"/></p>

<form action="BookManagement_Add_Books_Copy">
	<button class="btn btn-primary" name="submit" type="submit">Add
		Copy</button>
</form>